### ISSUE TITLE
Canvas tag issue

### ISSUE THREAD

**Issue by brenwell** [izolate/html2pug#10]
Thanks for the tool, thought you may be interested in knowing that their is an issue with the canvas tag

**Input**

```html
<div>
  <canvas id="canvas"></canvas>
  <p>where did this paragraph go</p>
</div>
```

**Output**
```pug
div
  canvas(style='')

```

**Comment by izolate** [comment]
@brenwell Thanks for the report - this is fixed in `1.0.0`
