### ISSUE TITLE
Why the command can't work

### ISSUE THREAD

**Issue by Andrewyg** [izolate/html2pug#23]
I run the command `html2pug < inbox.html > test.pug` and it shows this error

![image](https://user-images.githubusercontent.com/20808546/29250649-cebd1e00-8078-11e7-8f6b-6fa655ed407f.png)

**Comment by izolate** [comment]
@Andrewyg What Node.js version are you using? Please ensure you're on at least `7.6`

**Comment by Andrewyg** [comment]
v6.10.3

**Comment by Andrewyg** [comment]
but the stable version only reaches v6.11.2

**Comment by Andrewyg** [comment]
do you have app work with 6.11.2 since nvm sucks

**Comment by izolate** [comment]
@Andrewyg Sorry, I'm not supporting anything lower than `7.6`. The next stable LTS is `8.x` starting in 2 months. It's okay to upgrade :)

**Comment by Andrewyg** [comment]
I'm using window and my path contains space so I think is this reason cause it not working,
I'm booting my CentOS7 in VM to test it out
But thanks.

**Comment by izolate** [comment]
@Andrewyg nvm doesn't natively run on Windows. I recommend installing the [Windows Subsystem for Linux](https://msdn.microsoft.com/en-us/commandline/wsl/about) and running nvm on that.

**Comment by Andrewyg** [comment]
Thanks :)
