### ISSUE TITLE
Double quotes support?

### ISSUE THREAD

**Issue by 7iomka** [izolate/html2pug#37]
Hello. I use vscode and prefer to use extension [vscode-html2pug](https://github.com/dbalas/vscode-html2pug/issues/4), based on your plugin.
In my env, I use double quotes in pug. It is possible to change preferable type of quotes? 
Currently, I needed every time to manually replace single quotes, and it is hard to do(
Thanks!

**Comment by izolate** [comment]
Hi @7iomka, thanks for reporting this. Added option `doubleQuotes` in [`4.0.0`](https://github.com/izolate/html2pug/releases/tag/v4.0.0)
