### ISSUE TITLE
Letters Inconsistent 

### ISSUE THREAD

**Issue by emn178** [izolate/html2pug#4]
Hi,

Input

``` HTML
<i class="fa fa-check" *ngIf="todo.done"></i>
```

Result

``` Pug
i.fa.fa-check(*ngif='todo.done')
```

Expect

``` Pug
i.fa.fa-check(*ngIf='todo.done')
```

It should keep origin letters.

**Comment by izolate** [comment]
Bad news. This would be nice to have, but HTML tags/attributes are case insensitive and there's no support for case sensitivity in the HTML parser used in this package.

See:
* inikulin/parse5/issues/116
* inikulin/parse5/issues/133
* inikulin/parse5/issues/172
