### ISSUE TITLE
Encode accents

### ISSUE THREAD

**Issue by brunowego** [izolate/html2pug#5]
Think about a option to not encode accents! 

Thanks.

**Comment by izolate** [comment]
@brunowego Version `1.0.0` doesn't encode them:

This:
```html
<p class="accents">â, é, ï, õ, ù</p>
```

Becomes:
```pug
p.accents â, é, ï, õ, ù
```

Is this the outcome you're looking for?

**Comment by brunowego** [comment]
@izolate thanks for this feedback. This is old and I no longer remember what I needed. 🤔
